from dataclasses import dataclass
from typing import Dict, Optional


@dataclass(frozen=True)
class ErrorSpec:
    code: str
    domain: str
    name: str
    severity: str
    recoverable: bool
    description: str
    probable_cause: str
    recommended_action: str
    stage: Optional[str] = None
    severity_level: Optional[int] = None
    severity_label: Optional[str] = None
    retryable: Optional[bool] = None
    integrity_impact: Optional[bool] = None
    short_pt: Optional[str] = None
    detailed_pt: Optional[str] = None
    probable_causes_pt: Optional[str] = None
    recommended_actions_pt: Optional[str] = None


ERROR_TABLE: Dict[str, ErrorSpec] = {
    "MS-SNP-001": ErrorSpec(
        "MS-SNP-001", "SNP", "SnapshotPowerShellFailure", "ERROR", True,
        "Falha ao executar PowerShell do snapshot.",
        "Runner falhou/timeout/erro de execução.",
        "Verificar runner, stderr e permissões.",
        stage="snapshot",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=False,
        short_pt="Falha ao executar snapshot PowerShell.",
        detailed_pt="A coleta de snapshot falhou antes de produzir dados válidos.",
        probable_causes_pt="Runner com falha de execução, timeout ou erro de ambiente.",
        recommended_actions_pt="Validar permissões, stderr e estabilidade do runner PowerShell.",
    ),
    "MS-SNP-002": ErrorSpec(
        "MS-SNP-002", "SNP", "SnapshotJsonInvalid", "ERROR", True,
        "Snapshot retornou JSON inválido.",
        "Ruído no stdout ou erro no script de snapshot.",
        "Inspecionar stdout bruto e corrigir serialização.",
        stage="snapshot",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=False,
        short_pt="Snapshot retornou JSON inválido.",
        detailed_pt="A saída do snapshot não pôde ser desserializada com segurança.",
        probable_causes_pt="Ruído no stdout ou quebra de serialização no script PowerShell.",
        recommended_actions_pt="Capturar stdout bruto e corrigir a emissão JSON do snapshot.",
    ),
    "MS-SEL-002": ErrorSpec(
        "MS-SEL-002", "SEL", "DiskBlockedByPolicy", "ERROR", False,
        "Disco bloqueado por política.",
        "Disco 0/boot/system/offline/bloqueado.",
        "Selecionar disco elegível.",
        stage="selection",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=True,
        short_pt="Disco bloqueado pela política.",
        detailed_pt="A seleção foi negada por guard rails de segurança operacional.",
        probable_causes_pt="Disco interno, boot/system, offline ou explicitamente bloqueado.",
        recommended_actions_pt="Selecionar apenas disco removível/elegível conforme política.",
    ),
    "MS-GRD-001": ErrorSpec(
        "MS-GRD-001", "GRD", "DiskIdentityMismatch", "CRITICAL", False,
        "Violação de identidade física detectada.",
        "Drift de identidade relevante.",
        "Revalidar disco e repetir operação.",
        stage="guardian",
        severity_level=4,
        severity_label="CRITICAL",
        retryable=False,
        integrity_impact=True,
        short_pt="Violação de identidade física.",
        detailed_pt="A identidade do disco mudou entre etapas críticas do pipeline.",
        probable_causes_pt="Reenumeração, troca de dispositivo ou inconsistência de identificação.",
        recommended_actions_pt="Interromper operação, revalidar identidade e reiniciar fluxo.",
    ),
    "MS-USB-003": ErrorSpec(
        "MS-USB-003", "USB", "RemovableDeviceNotReacquired", "ERROR", True,
        "Dispositivo removível não foi re-adquirido.",
        "Reenumeração/desconexão durante operação.",
        "Reconectar dispositivo e tentar novamente.",
        stage="postcheck",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=True,
        short_pt="Dispositivo removível não re-adquirido.",
        detailed_pt="O dispositivo alvo não foi encontrado após etapa crítica de operação.",
        probable_causes_pt="Desconexão física, reenumeração ou alteração de identidade.",
        recommended_actions_pt="Reconectar dispositivo e repetir fluxo completo com nova validação.",
    ),
    "MS-RUN-001": ErrorSpec(
        "MS-RUN-001", "RUN", "WorkerSpawnFailed", "ERROR", True,
        "Falha ao iniciar processo do worker PowerShell.",
        "Processo não foi criado pelo runner.",
        "Verificar disponibilidade do PowerShell e permissões de execução.",
        stage="runner",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=False,
        short_pt="Falha ao iniciar worker.",
        detailed_pt="O processo de worker não foi iniciado no runner PowerShell.",
        probable_causes_pt="PowerShell ausente, bloqueio de execução ou erro de criação de processo.",
        recommended_actions_pt="Validar comando, path do script e permissões de execução.",
    ),
    "MS-RUN-002": ErrorSpec(
        "MS-RUN-002", "RUN", "PowerShellTimeout", "ERROR", True,
        "Execução PowerShell excedeu timeout.",
        "Comando travado/lento.",
        "Aumentar timeout e investigar IO/disco.",
        stage="runner",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=False,
        short_pt="Timeout na execução PowerShell.",
        detailed_pt="A execução excedeu o tempo limite definido para a etapa de runner.",
        probable_causes_pt="Operação bloqueada, I/O lento ou comando em estado de espera.",
        recommended_actions_pt="Inspecionar processo, stdout/stderr e saúde do dispositivo.",
    ),
    "MS-RUN-003": ErrorSpec(
        "MS-RUN-003", "RUN", "WorkerReturnedInvalidJson", "ERROR", True,
        "Worker retornou JSON inválido.",
        "Ruído em stdout ou contrato quebrado.",
        "Padronizar saída JSON compacta.",
        stage="runner",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=False,
        short_pt="Saída inválida do worker.",
        detailed_pt="O worker finalizou sem fornecer payload JSON consumível.",
        probable_causes_pt="Ruído no stdout, contrato quebrado ou erro de serialização.",
        recommended_actions_pt="Ajustar worker para emitir apenas JSON válido no stdout.",
    ),
    "MS-IPC-001": ErrorSpec(
        "MS-IPC-001", "IPC", "WorkerStdoutEmpty", "ERROR", True,
        "Worker retornou stdout vazio.",
        "Processo executou sem payload de resposta.",
        "Inspecionar execução do worker e geração de resultado final.",
        stage="ipc",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=False,
        short_pt="Stdout do worker vazio.",
        detailed_pt="Nenhuma resposta foi emitida no canal esperado de IPC.",
        probable_causes_pt="Falha silenciosa no script ou desvio de fluxo sem retorno JSON.",
        recommended_actions_pt="Garantir emissão de resultado JSON em todos os caminhos de execução.",
    ),
    "MS-IPC-002": ErrorSpec(
        "MS-IPC-002", "IPC", "WorkerJsonNotFound", "ERROR", True,
        "JSON não encontrado na saída do worker.",
        "Saída sem objeto JSON detectável.",
        "Remover ruído do stdout e padronizar emissão JSON.",
        stage="ipc",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=False,
        short_pt="JSON ausente no stdout.",
        detailed_pt="A camada de IPC não encontrou bloco JSON na resposta do worker.",
        probable_causes_pt="Logs misturados no stdout ou saída incompleta.",
        recommended_actions_pt="Separar logs para stderr e manter stdout exclusivamente para JSON.",
    ),
    "MS-IPC-003": ErrorSpec(
        "MS-IPC-003", "IPC", "WorkerJsonInvalid", "ERROR", True,
        "JSON do worker é inválido.",
        "Payload não pôde ser desserializado.",
        "Corrigir serialização no worker.",
        stage="ipc",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=False,
        short_pt="JSON inválido no IPC.",
        detailed_pt="O payload emitido existe, mas está malformado para parse seguro.",
        probable_causes_pt="Escape incorreto de caracteres ou truncamento da saída.",
        recommended_actions_pt="Validar JSON no worker antes de emitir resposta final.",
    ),
    "MS-IPC-004": ErrorSpec(
        "MS-IPC-004", "IPC", "WorkerContractFieldMissing", "ERROR", True,
        "Campo obrigatório ausente no contrato IPC.",
        "Schema retornado sem chave obrigatória.",
        "Atualizar worker para respeitar contrato mínimo.",
        stage="ipc",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=False,
        short_pt="Campo obrigatório ausente no IPC.",
        detailed_pt="O worker retornou JSON sem todas as chaves exigidas pelo contrato.",
        probable_causes_pt="Versão de worker incompatível ou regressão no script.",
        recommended_actions_pt="Restaurar contrato mínimo obrigatório entre Python e worker.",
    ),
    "MS-IPC-005": ErrorSpec(
        "MS-IPC-005", "IPC", "WorkerFailureReported", "ERROR", True,
        "Worker reportou falha operacional.",
        "Campo Success=false no retorno IPC.",
        "Inspecionar ErrorCode/ErrorMessage/PipelineErrorCode do worker.",
        stage="ipc",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=True,
        short_pt="Worker reportou falha.",
        detailed_pt="O próprio worker informou falha ao concluir a operação de mídia.",
        probable_causes_pt="Falha em rebuild, partição, formatação ou verificação local do worker.",
        recommended_actions_pt="Classificar pelo PipelineErrorCode e executar ação corretiva específica.",
    ),
    "MS-IPC-006": ErrorSpec(
        "MS-IPC-006", "IPC", "WorkerUnexpectedSchema", "ERROR", True,
        "Schema inesperado no retorno do worker.",
        "Contrato retornado com estrutura incompatível.",
        "Alinhar schema do worker ao contrato esperado.",
        stage="ipc",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=False,
        short_pt="Schema IPC inesperado.",
        detailed_pt="A resposta possui formato estrutural incompatível com o parser Python.",
        probable_causes_pt="Mudança não coordenada no JSON do worker.",
        recommended_actions_pt="Sincronizar contratos e validar compatibilidade antes de deploy.",
    ),
    "MS-DSK-003": ErrorSpec(
        "MS-DSK-003", "DSK", "DiskWipeFailed", "ERROR", True,
        "Falha ao limpar disco.",
        "Clear-Disk falhou.",
        "Verificar proteção/read-only/estado do hardware.",
        stage="disk_ops",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=True,
        short_pt="Falha ao limpar disco.",
        detailed_pt="A etapa de limpeza do disco falhou antes de concluir o rebuild determinístico.",
        probable_causes_pt="Read-only, acesso negado ou erro de hardware.",
        recommended_actions_pt="Verificar estado do disco e repetir operação com evidência de erro.",
    ),
    "MS-DSK-005": ErrorSpec(
        "MS-DSK-005", "DSK", "PartitionCreationFailed", "ERROR", True,
        "Falha ao criar partição.",
        "New-Partition falhou.",
        "Revalidar estado MBR e espaço do dispositivo.",
        stage="disk_ops",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=True,
        short_pt="Falha na criação da partição.",
        detailed_pt="A partição primária não foi criada após inicialização do disco.",
        probable_causes_pt="Estado inconsistente do disco ou erro de comando de partição.",
        recommended_actions_pt="Refazer rebuild e validar evidências de partição após execução.",
    ),
    "MS-FMT-001": ErrorSpec(
        "MS-FMT-001", "FMT", "Fat32FormatFailed", "ERROR", True,
        "Falha na formatação FAT32.",
        "fat32format.exe retornou erro.",
        "Checar argumentos, letra e integridade do executável.",
        stage="format",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=True,
        short_pt="Falha na formatação FAT32.",
        detailed_pt="A etapa de formatação FAT32 não concluiu com sucesso no worker.",
        probable_causes_pt="Erro no executável de formatação, letra inválida ou estado inconsistente.",
        recommended_actions_pt="Validar executável, parâmetros e estado da partição antes de repetir.",
    ),
    "MS-FMT-002": ErrorSpec(
        "MS-FMT-002", "FMT", "ExFatFormatFailed", "ERROR", True,
        "Falha na formatação exFAT.",
        "Format-Volume falhou.",
        "Checar estado da partição/volume.",
        stage="format",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=True,
        short_pt="Falha na formatação exFAT.",
        detailed_pt="A etapa de formatação exFAT não concluiu conforme esperado.",
        probable_causes_pt="Falha do Format-Volume ou inconsistência no volume alvo.",
        recommended_actions_pt="Revalidar partição, drive letter e repetir formatação.",
    ),
    "MS-FMT-004": ErrorSpec(
        "MS-FMT-004", "FMT", "InvalidFat32ClusterSize", "ERROR", False,
        "Cluster FAT32 divergente do perfil PS2.",
        "AUS != 32KB.",
        "Refazer formatação com -c32 e validar BlockSize.",
        stage="format",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=True,
        short_pt="Cluster FAT32 inválido.",
        detailed_pt="O tamanho de cluster FAT32 não atende à política determinística.",
        probable_causes_pt="Parâmetro de cluster incorreto ou formatação fora do perfil definido.",
        recommended_actions_pt="Refazer formatação com cluster exigido e confirmar evidência de BlockSize.",
    ),
    "MS-VOL-001": ErrorSpec(
        "MS-VOL-001", "VOL", "DriveLetterMissing", "ERROR", True,
        "Volume sem drive letter após operação.",
        "Partição criada sem letra atribuída.",
        "Atribuir drive letter e revalidar.",
        stage="verify",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=True,
        short_pt="Letra de unidade ausente.",
        detailed_pt="A verificação encontrou volume sem drive letter utilizável.",
        probable_causes_pt="Falha na atribuição automática de letra ou conflito de montagem.",
        recommended_actions_pt="Forçar atribuição de letra livre e repetir verificação.",
    ),
    "MS-VOL-003": ErrorSpec(
        "MS-VOL-003", "VOL", "BlockSizeUnavailable", "ERROR", True,
        "BlockSize indisponível para validação.",
        "Evidência do volume não retornou BlockSize.",
        "Reconsultar volume e validar coleta de evidência.",
        stage="verify",
        severity_level=3,
        severity_label="ERROR",
        retryable=True,
        integrity_impact=False,
        short_pt="BlockSize indisponível.",
        detailed_pt="A telemetria de volume não trouxe tamanho de bloco para validação.",
        probable_causes_pt="Consulta de evidência incompleta ou atraso de atualização de volume.",
        recommended_actions_pt="Reexecutar leitura de evidência e manter trilha de stdout/stderr.",
    ),
    "MS-VFY-001": ErrorSpec(
        "MS-VFY-001", "VFY", "PartitionStyleMismatch", "ERROR", False,
        "PartitionStyle divergente do esperado.",
        "Initialize-Disk não resultou em MBR.",
        "Refazer etapa de inicialização e verificar disco alvo.",
        stage="verify",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=True,
        short_pt="PartitionStyle divergente.",
        detailed_pt="A verificação final detectou estilo de partição diferente da política.",
        probable_causes_pt="Falha na conversão para MBR ou seleção incorreta de disco.",
        recommended_actions_pt="Reiniciar pipeline com validação de identidade e estilo de partição.",
    ),
    "MS-VFY-002": ErrorSpec(
        "MS-VFY-002", "VFY", "PartitionMissingAfterSuccess", "ERROR", False,
        "Partição/volume ausente após sucesso reportado.",
        "Reenumeração/erro de criação/estado inconsistente.",
        "Reexecutar pipeline com reaquisição por identidade.",
        stage="verify",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=True,
        short_pt="Partição ausente após sucesso.",
        detailed_pt="A evidência final não confirmou partição/volume apesar de sucesso anterior.",
        probable_causes_pt="Reenumeração, falha tardia de criação ou estado inconsistente do disco.",
        recommended_actions_pt="Executar novo ciclo com validação de identidade e evidências completas.",
    ),
    "MS-VFY-003": ErrorSpec(
        "MS-VFY-003", "VFY", "FileSystemMismatch", "ERROR", False,
        "Filesystem divergente do solicitado.",
        "Formato observado não corresponde ao formato requerido.",
        "Refazer formatação com filesystem correto e revalidar.",
        stage="verify",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=True,
        short_pt="Filesystem divergente.",
        detailed_pt="A verificação final encontrou sistema de arquivos diferente do solicitado.",
        probable_causes_pt="Formatação parcial, volume incorreto ou inconsistência de evidência.",
        recommended_actions_pt="Refazer pipeline garantindo alvo correto e conferência pós-format.",
    ),
    "MS-VFY-004": ErrorSpec(
        "MS-VFY-004", "VFY", "BlockSizeMismatch", "ERROR", False,
        "BlockSize divergente da política.",
        "Tamanho de bloco não atende requisito operacional.",
        "Refazer formatação com política de bloco correta.",
        stage="verify",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=True,
        short_pt="BlockSize divergente.",
        detailed_pt="O tamanho de bloco final não está de acordo com a política ativa.",
        probable_causes_pt="Parâmetros de formatação incorretos ou evidência lida do volume errado.",
        recommended_actions_pt="Reformatar com parâmetros corretos e validar evidência final.",
    ),
    "MS-VFY-005": ErrorSpec(
        "MS-VFY-005", "VFY", "UnexpectedPartitionCount", "ERROR", False,
        "Quantidade de partições inesperada.",
        "Número de partições não corresponde ao contrato.",
        "Reconstruir disco para partição única e verificar novamente.",
        stage="verify",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=True,
        short_pt="Contagem de partições inesperada.",
        detailed_pt="A verificação detectou mais/menos partições do que o esperado.",
        probable_causes_pt="Rebuild incompleto, interferência externa ou estado residual do disco.",
        recommended_actions_pt="Executar limpeza determinística e criar partição única.",
    ),
    "MS-VFY-006": ErrorSpec(
        "MS-VFY-006", "VFY", "VerifySuccessContractBroken", "ERROR", False,
        "Sucesso reportado incompatível com evidências.",
        "Contrato de sucesso foi quebrado na verificação final.",
        "Tratar como falha de verify e investigar inconsistência.",
        stage="verify",
        severity_level=4,
        severity_label="CRITICAL",
        retryable=False,
        integrity_impact=True,
        short_pt="Contrato de sucesso quebrado.",
        detailed_pt="Resultado de sucesso não foi confirmado por evidência operacional final.",
        probable_causes_pt="Retorno otimista do worker ou drift entre execução e inspeção final.",
        recommended_actions_pt="Classificar como falha crítica, persistir evidência e bloquear conclusão.",
    ),
    "MS-POL-001": ErrorSpec(
        "MS-POL-001", "POL", "FilesystemPolicyViolation", "ERROR", False,
        "Violação de política de filesystem.",
        "Filesystem solicitado não atende política ativa.",
        "Aplicar somente formatos permitidos pela política.",
        stage="policy",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=True,
        short_pt="Violação de política de filesystem.",
        detailed_pt="A solicitação operacional conflita com política interna de filesystem.",
        probable_causes_pt="Parâmetro inválido ou fluxo externo sem alinhamento de política.",
        recommended_actions_pt="Corrigir solicitação para formato permitido e repetir processo.",
    ),
    "MS-POL-002": ErrorSpec(
        "MS-POL-002", "POL", "ReadyStateContractViolation", "ERROR", False,
        "Estado READY não atende contrato mínimo.",
        "Critérios de prontidão insuficientes para operação segura.",
        "Revalidar evidências antes de marcar READY.",
        stage="policy",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=True,
        short_pt="Contrato READY violado.",
        detailed_pt="O disco não possui evidência suficiente para estado READY seguro.",
        probable_causes_pt="Critérios permissivos ou ausência de validações complementares.",
        recommended_actions_pt="Aprimorar verificação e exigir evidências mínimas obrigatórias.",
    ),
    "MS-POL-003": ErrorSpec(
        "MS-POL-003", "POL", "InternalDiskOperationForbidden", "CRITICAL", False,
        "Operação em disco interno proibida por política.",
        "Tentativa de execução fora do escopo permitido.",
        "Bloquear operação e revisar seleção do alvo.",
        stage="policy",
        severity_level=4,
        severity_label="CRITICAL",
        retryable=False,
        integrity_impact=True,
        short_pt="Operação proibida em disco interno.",
        detailed_pt="Foi detectada tentativa de operação em disco não elegível por política.",
        probable_causes_pt="Seleção incorreta de alvo ou bypass indevido de validações.",
        recommended_actions_pt="Interromper fluxo e exigir nova seleção em disco removível.",
    ),
    "MS-SYS-001": ErrorSpec(
        "MS-SYS-001", "SYS", "AdminPrivilegesRequired", "ERROR", False,
        "Privilégios de administrador são obrigatórios.",
        "Execução sem elevação suficiente.",
        "Executar processo com privilégios administrativos.",
        stage="system",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=False,
        short_pt="Privilégios administrativos ausentes.",
        detailed_pt="A operação exige permissões elevadas para comandos de disco.",
        probable_causes_pt="Execução em contexto sem privilégios adequados.",
        recommended_actions_pt="Reiniciar aplicação em modo administrador.",
    ),
    "MS-SYS-003": ErrorSpec(
        "MS-SYS-003", "SYS", "RequiredAssetMissing", "ERROR", False,
        "Asset obrigatório não encontrado.",
        "Script/binário requerido está ausente.",
        "Restaurar arquivos obrigatórios do pacote.",
        stage="system",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=False,
        short_pt="Asset obrigatório ausente.",
        detailed_pt="Um artefato necessário para execução não foi localizado.",
        probable_causes_pt="Instalação incompleta ou caminho de assets inválido.",
        recommended_actions_pt="Validar pacote de assets e caminhos configurados.",
    ),
    "MS-CFG-001": ErrorSpec(
        "MS-CFG-001", "CFG", "InvalidOperationConfiguration", "ERROR", False,
        "Configuração de operação inválida.",
        "Parâmetros de execução não atendem contrato.",
        "Corrigir configuração antes de executar operação.",
        stage="config",
        severity_level=3,
        severity_label="ERROR",
        retryable=False,
        integrity_impact=False,
        short_pt="Configuração inválida.",
        detailed_pt="A configuração recebida não atende pré-condições contratuais.",
        probable_causes_pt="Parâmetros ausentes, inválidos ou inconsistentes.",
        recommended_actions_pt="Validar e normalizar configuração antes de iniciar pipeline.",
    ),
    "MS-AUD-001": ErrorSpec(
        "MS-AUD-001", "AUD", "AuditWriteFailure", "WARN", True,
        "Falha ao gravar evento de auditoria.",
        "IO/log path inválido.",
        "Corrigir diretório de logs/permissões.",
        stage="audit",
        severity_level=2,
        severity_label="WARN",
        retryable=True,
        integrity_impact=False,
        short_pt="Falha de escrita na auditoria.",
        detailed_pt="O evento não pôde ser persistido no arquivo principal de auditoria.",
        probable_causes_pt="Permissões insuficientes, diretório inválido ou IO indisponível.",
        recommended_actions_pt="Corrigir permissões/caminho e manter fallback habilitado.",
    ),
}
