from dataclasses import dataclass, field
from typing import Dict, List, Optional


# Semântica de severidade operacional:
# 1 = Warning
# 2 = Recoverable
# 3 = Operational Failure
# 4 = Critical Integrity
@dataclass(frozen=True)
class ErrorSpec:
    code: str
    domain: str
    name: str
    severity: str
    recoverable: bool
    description: str
    probable_cause: str
    recommended_action: str
    stage: Optional[str] = None
    severity_level: Optional[int] = None
    severity_label: Optional[str] = None
    retryable: Optional[bool] = None
    integrity_impact: Optional[bool] = None
    short_pt: Optional[str] = None
    detailed_pt: Optional[str] = None
    probable_causes_pt: List[str] = field(default_factory=list)
    recommended_actions_pt: List[str] = field(default_factory=list)


ERROR_TABLE: Dict[str, ErrorSpec] = {
    "MS-SNP-001": ErrorSpec(
        "MS-SNP-001", "SNP", "SnapshotPowerShellFailure", "ERROR", True,
        "Falha ao executar PowerShell do snapshot.",
        "Runner falhou/timeout/erro de execução.",
        "Verificar runner, stderr e permissões.",
        stage="snapshot", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=False,
        short_pt="Falha ao executar snapshot PowerShell.",
        detailed_pt="A etapa de snapshot falhou antes de retornar evidência válida.",
        probable_causes_pt=["Falha de execução no PowerShell.", "Timeout no comando de snapshot."],
        recommended_actions_pt=["Inspecionar stderr do runner.", "Validar permissões administrativas."],
    ),
    "MS-SNP-002": ErrorSpec(
        "MS-SNP-002", "SNP", "SnapshotJsonInvalid", "ERROR", True,
        "Snapshot retornou JSON inválido.",
        "Ruído no stdout ou erro no script de snapshot.",
        "Inspecionar stdout bruto e corrigir serialização.",
        stage="snapshot", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=False,
        short_pt="JSON inválido no snapshot.",
        detailed_pt="O retorno do snapshot não pôde ser desserializado com segurança.",
        probable_causes_pt=["Logs misturados ao JSON no stdout.", "Serialização quebrada no script de snapshot."],
        recommended_actions_pt=["Separar logs e payload JSON.", "Corrigir serialização no script PowerShell."],
    ),
    "MS-SEL-002": ErrorSpec(
        "MS-SEL-002", "SEL", "DiskBlockedByPolicy", "ERROR", False,
        "Disco bloqueado por política.",
        "Disco 0/boot/system/offline/bloqueado.",
        "Selecionar disco elegível.",
        stage="selection", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=True,
        short_pt="Disco bloqueado por política.",
        detailed_pt="A seleção foi recusada por violação de elegibilidade do disco.",
        probable_causes_pt=["Disco interno/boot/system.", "Disco offline ou marcado como bloqueado."],
        recommended_actions_pt=["Selecionar dispositivo removível elegível.", "Atualizar snapshot antes de nova seleção."],
    ),
    "MS-GRD-001": ErrorSpec(
        "MS-GRD-001", "GRD", "DiskIdentityMismatch", "CRITICAL", False,
        "Violação de identidade física detectada.",
        "Drift de identidade relevante.",
        "Revalidar disco e repetir operação.",
        stage="guardian", severity_level=4, severity_label="CRITICAL", retryable=False, integrity_impact=True,
        short_pt="Violação de identidade física.",
        detailed_pt="A identidade observada divergiu da identidade originalmente validada.",
        probable_causes_pt=["Reenumeração de dispositivo.", "Troca física de mídia durante a operação."],
        recommended_actions_pt=["Interromper pipeline.", "Revalidar identidade antes de nova execução."],
    ),

    "MS-RUN-001": ErrorSpec(
        "MS-RUN-001", "RUN", "WorkerSpawnFailed", "ERROR", True,
        "Falha ao iniciar processo do worker.",
        "Runner não conseguiu criar processo PowerShell.",
        "Verificar execução do PowerShell e permissões.",
        stage="runner", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=False,
        short_pt="Falha ao iniciar worker.",
        detailed_pt="O processo do worker não foi criado pela camada runner.",
        probable_causes_pt=["PowerShell indisponível.", "Path de script inválido."],
        recommended_actions_pt=["Validar caminho do script.", "Verificar políticas de execução."],
    ),
    "MS-RUN-002": ErrorSpec(
        "MS-RUN-002", "RUN", "WorkerTimeout", "ERROR", True,
        "Execução PowerShell excedeu timeout.",
        "Comando travado/lento.",
        "Aumentar timeout e investigar IO/disco.",
        stage="runner", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=False,
        short_pt="Timeout na execução do worker.",
        detailed_pt="O worker não concluiu dentro da janela de timeout configurada.",
        probable_causes_pt=["Operação de disco bloqueada.", "I/O lento no dispositivo alvo."],
        recommended_actions_pt=["Revisar timeout operacional.", "Coletar tail de stdout/stderr para análise."],
    ),
    "MS-RUN-003": ErrorSpec(
        "MS-RUN-003", "RUN", "WorkerProcessFailed", "ERROR", True,
        "Falha na execução do processo do worker.",
        "Processo retornou erro ou saída inconsistente.",
        "Inspecionar código de saída e stderr do worker.",
        stage="runner", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=False,
        short_pt="Falha de processo do worker.",
        detailed_pt="O processo finalizou com falha operacional na etapa de runner.",
        probable_causes_pt=["Exit code não zero.", "Falha de execução no script PowerShell."],
        recommended_actions_pt=["Capturar stderr completo.", "Classificar falha por subetapa para próxima ação."],
    ),

    "MS-IPC-001": ErrorSpec(
        "MS-IPC-001", "IPC", "WorkerStdoutEmpty", "ERROR", True,
        "Worker retornou stdout vazio.",
        "Nenhum payload foi emitido pelo worker.",
        "Verificar fluxo de saída e retorno final do worker.",
        stage="ipc", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=False,
        short_pt="Stdout do worker vazio.",
        detailed_pt="A camada IPC não recebeu dados no stdout esperado.",
        probable_causes_pt=["Fluxo de retorno não executado.", "Falha silenciosa no script."],
        recommended_actions_pt=["Garantir emissão de JSON em todos os caminhos.", "Separar logs em stderr."],
    ),
    "MS-IPC-002": ErrorSpec(
        "MS-IPC-002", "IPC", "WorkerJsonNotFound", "ERROR", True,
        "JSON não encontrado na saída do worker.",
        "Stdout sem objeto JSON detectável.",
        "Padronizar emissão de JSON único no stdout.",
        stage="ipc", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=False,
        short_pt="JSON ausente no stdout.",
        detailed_pt="A camada de parsing não encontrou payload JSON válido.",
        probable_causes_pt=["Ruído textual no stdout.", "Formato de saída inesperado."],
        recommended_actions_pt=["Emitir apenas JSON no stdout.", "Redirecionar logs técnicos para stderr."],
    ),
    "MS-IPC-003": ErrorSpec(
        "MS-IPC-003", "IPC", "WorkerJsonInvalid", "ERROR", True,
        "JSON do worker é inválido.",
        "Payload não pôde ser desserializado.",
        "Corrigir serialização no worker.",
        stage="ipc", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=False,
        short_pt="JSON inválido no IPC.",
        detailed_pt="O payload foi recebido, mas está malformado para parsing.",
        probable_causes_pt=["Escape incorreto de caracteres.", "Payload truncado."],
        recommended_actions_pt=["Validar JSON antes da emissão.", "Incluir teste de contrato no worker."],
    ),
    "MS-IPC-004": ErrorSpec(
        "MS-IPC-004", "IPC", "WorkerContractFieldMissing", "ERROR", False,
        "Campo obrigatório ausente no contrato IPC.",
        "Schema retornado não contém todos os campos necessários.",
        "Ajustar worker para cumprir o contrato mínimo.",
        stage="ipc", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=False,
        short_pt="Campo obrigatório ausente no IPC.",
        detailed_pt="O contrato entre Python e worker foi quebrado por chave ausente.",
        probable_causes_pt=["Regressão no script do worker.", "Versão de worker incompatível."],
        recommended_actions_pt=["Restaurar campos obrigatórios.", "Versionar contrato IPC."],
    ),
    "MS-IPC-005": ErrorSpec(
        "MS-IPC-005", "IPC", "WorkerFailureReported", "ERROR", True,
        "Worker reportou falha.",
        "Success=false no retorno IPC.",
        "Classificar por PipelineErrorCode e agir por causa raiz.",
        stage="ipc", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=True,
        short_pt="Falha reportada pelo worker.",
        detailed_pt="O worker concluiu com indicação explícita de falha operacional.",
        probable_causes_pt=["Erro em rebuild/formatação/verificação local.", "Condição de disco incompatível."],
        recommended_actions_pt=["Persistir payload completo do worker.", "Aplicar ação corretiva por código de erro."],
    ),
    "MS-IPC-006": ErrorSpec(
        "MS-IPC-006", "IPC", "WorkerUnexpectedSchema", "ERROR", False,
        "Schema inesperado no retorno do worker.",
        "Estrutura retornada incompatível com o parser.",
        "Alinhar schema retornado ao contrato esperado.",
        stage="ipc", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=False,
        short_pt="Schema inesperado no IPC.",
        detailed_pt="A resposta foi recebida, porém com estrutura não compatível.",
        probable_causes_pt=["Mudança não coordenada de contrato.", "Payload parcial/estrutural."],
        recommended_actions_pt=["Sincronizar versões entre Python e worker.", "Aplicar validação de schema."],
    ),

    "MS-DSK-003": ErrorSpec(
        "MS-DSK-003", "DSK", "DiskWipeFailed", "ERROR", True,
        "Falha ao limpar disco.",
        "Clear-Disk falhou.",
        "Verificar proteção/read-only/estado do hardware.",
        stage="disk", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=True,
        short_pt="Falha ao limpar disco.",
        detailed_pt="A etapa de limpeza não conseguiu preparar o disco para rebuild.",
        probable_causes_pt=["Disco em modo read-only.", "Erro de acesso ao dispositivo."],
        recommended_actions_pt=["Remover proteção de escrita.", "Repetir operação após reaquisição."],
    ),
    "MS-DSK-005": ErrorSpec(
        "MS-DSK-005", "DSK", "PartitionCreationFailed", "ERROR", True,
        "Falha ao criar partição.",
        "New-Partition falhou.",
        "Revalidar estado MBR e espaço do dispositivo.",
        stage="disk", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=True,
        short_pt="Falha na criação da partição.",
        detailed_pt="A partição primária não foi criada após inicialização.",
        probable_causes_pt=["Estado inconsistente de tabela de partição.", "Falha de comando de particionamento."],
        recommended_actions_pt=["Executar rebuild determinístico novamente.", "Validar contagem de partições após operação."],
    ),

    "MS-FMT-001": ErrorSpec(
        "MS-FMT-001", "FMT", "Fat32FormatFailed", "ERROR", True,
        "Falha na formatação FAT32.",
        "fat32format.exe retornou erro.",
        "Checar argumentos, letra e integridade do executável.",
        stage="format", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=True,
        short_pt="Falha na formatação FAT32.",
        detailed_pt="A formatação FAT32 não concluiu com sucesso operacional.",
        probable_causes_pt=["Falha no utilitário de formatação.", "Drive letter inválido."],
        recommended_actions_pt=["Validar argumentos de execução.", "Conferir estado da partição antes de repetir."],
    ),
    "MS-FMT-002": ErrorSpec(
        "MS-FMT-002", "FMT", "ExFatFormatFailed", "ERROR", True,
        "Falha na formatação exFAT.",
        "Format-Volume falhou.",
        "Checar estado da partição/volume.",
        stage="format", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=True,
        short_pt="Falha na formatação exFAT.",
        detailed_pt="A formatação exFAT não concluiu conforme esperado.",
        probable_causes_pt=["Falha no cmdlet Format-Volume.", "Volume não pronto para formatação."],
        recommended_actions_pt=["Revalidar volume e letra atribuída.", "Reexecutar após atualização de evidência."],
    ),
    "MS-FMT-004": ErrorSpec(
        "MS-FMT-004", "FMT", "InvalidFat32ClusterSize", "ERROR", False,
        "Cluster FAT32 divergente do perfil PS2.",
        "AUS != 32KB.",
        "Refazer formatação com -c32 e validar BlockSize.",
        stage="format", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=True,
        short_pt="Cluster FAT32 divergente da política.",
        detailed_pt="A verificação do cluster identificou valor diferente do definido pela política.",
        probable_causes_pt=["Parâmetro de cluster não aplicado.", "Leitura de evidência inconsistente."],
        recommended_actions_pt=["Não marcar disco como READY.", "Reexecutar formatação com cluster correto."],
    ),

    "MS-VOL-001": ErrorSpec(
        "MS-VOL-001", "VOL", "DriveLetterMissing", "ERROR", True,
        "Letra de unidade ausente após operação.",
        "Volume foi criado sem drive letter disponível.",
        "Atribuir letra e revalidar evidências.",
        stage="verify", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=True,
        short_pt="Letra de unidade ausente.",
        detailed_pt="A verificação final encontrou volume sem drive letter utilizável.",
        probable_causes_pt=["Falha na atribuição automática.", "Conflito com letras já ocupadas."],
        recommended_actions_pt=["Forçar atribuição de letra livre.", "Reexecutar leitura de volume."],
    ),
    "MS-VOL-003": ErrorSpec(
        "MS-VOL-003", "VOL", "BlockSizeUnavailable", "ERROR", True,
        "BlockSize indisponível para validação.",
        "Evidência de volume sem BlockSize.",
        "Reconsultar volume e repetir coleta de evidência.",
        stage="verify", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=False,
        short_pt="BlockSize indisponível.",
        detailed_pt="Não foi possível confirmar tamanho de bloco na verificação.",
        probable_causes_pt=["Atraso na atualização de metadados de volume.", "Consulta incompleta de evidência."],
        recommended_actions_pt=["Repetir leitura pós-operação.", "Persistir stdout/stderr para diagnóstico."],
    ),

    "MS-VFY-001": ErrorSpec(
        "MS-VFY-001", "VFY", "PartitionStyleMismatch", "ERROR", False,
        "PartitionStyle divergente do esperado.",
        "Initialize-Disk não resultou em MBR.",
        "Refazer etapa de inicialização e verificar disco alvo.",
        stage="verify", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=True,
        short_pt="PartitionStyle divergente.",
        detailed_pt="A verificação final encontrou estilo de partição diferente do esperado.",
        probable_causes_pt=["Conversão MBR não aplicada.", "Disco incorreto no alvo da operação."],
        recommended_actions_pt=["Revalidar identidade do disco.", "Refazer inicialização determinística."],
    ),
    "MS-VFY-002": ErrorSpec(
        "MS-VFY-002", "VFY", "PartitionMissingAfterSuccess", "ERROR", False,
        "Partição/volume ausente após sucesso reportado.",
        "Reenumeração/erro de criação/estado inconsistente.",
        "Reexecutar pipeline com reaquisição por identidade.",
        stage="verify", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=True,
        short_pt="Partição ausente após sucesso.",
        detailed_pt="O pós-check não encontrou partição/volume apesar de sucesso anterior.",
        probable_causes_pt=["Reenumeração do dispositivo.", "Falha tardia na criação de partição."],
        recommended_actions_pt=["Executar nova aquisição por identidade.", "Refazer pipeline completo."],
    ),
    "MS-VFY-003": ErrorSpec(
        "MS-VFY-003", "VFY", "FileSystemMismatch", "ERROR", False,
        "Filesystem divergente do solicitado.",
        "Evidência final diverge do filesystem esperado.",
        "Refazer formatação com filesystem correto.",
        stage="verify", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=True,
        short_pt="Filesystem divergente na verificação.",
        detailed_pt="A verificação final identificou filesystem diferente da solicitação.",
        probable_causes_pt=["Formato aplicado incorretamente.", "Leitura de volume não correspondente ao alvo."],
        recommended_actions_pt=["Não concluir operação como sucesso.", "Revalidar alvo e repetir formatação."],
    ),
    "MS-VFY-004": ErrorSpec(
        "MS-VFY-004", "VFY", "BlockSizeMismatch", "ERROR", False,
        "BlockSize divergente da política.",
        "Tamanho de bloco observado difere do esperado.",
        "Refazer formatação com política de bloco correta.",
        stage="verify", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=True,
        short_pt="Falha na verificação do tamanho de cluster.",
        detailed_pt="A verificação final identificou tamanho de cluster diferente da política definida para a operação.",
        probable_causes_pt=[
            "O worker aplicou cluster padrão do sistema.",
            "O parâmetro de cluster não foi repassado corretamente.",
            "A leitura pós-operação retornou evidência inconsistente.",
        ],
        recommended_actions_pt=[
            "Não marcar o disco como READY.",
            "Revalidar parâmetros enviados ao worker.",
            "Executar nova leitura de evidência antes de nova tentativa.",
        ],
    ),
    "MS-VFY-005": ErrorSpec(
        "MS-VFY-005", "VFY", "UnexpectedPartitionCount", "ERROR", False,
        "Contagem de partições inesperada.",
        "Quantidade observada diverge do contrato esperado.",
        "Reconstruir disco para partição única e revalidar.",
        stage="verify", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=True,
        short_pt="Contagem de partições inesperada.",
        detailed_pt="A verificação final encontrou número de partições fora da política.",
        probable_causes_pt=["Resíduo de partições anteriores.", "Falha parcial no rebuild."],
        recommended_actions_pt=["Executar limpeza completa do disco.", "Validar contagem após novo rebuild."],
    ),
    "MS-VFY-006": ErrorSpec(
        "MS-VFY-006", "VFY", "VerifySuccessContractBroken", "CRITICAL", False,
        "Sucesso reportado incompatível com evidências.",
        "Contrato de sucesso quebrado na verificação final.",
        "Tratar como falha crítica de integridade.",
        stage="verify", severity_level=4, severity_label="CRITICAL", retryable=False, integrity_impact=True,
        short_pt="Contrato de sucesso quebrado.",
        detailed_pt="A evidência observada contradiz o status de sucesso reportado anteriormente.",
        probable_causes_pt=["Retorno otimista do worker sem confirmação real.", "Drift entre execução e evidência final."],
        recommended_actions_pt=["Bloquear conclusão da operação.", "Persistir evidências para auditoria forense."],
    ),

    "MS-POL-001": ErrorSpec(
        "MS-POL-001", "POL", "FilesystemPolicyViolation", "ERROR", False,
        "Violação de política de filesystem.",
        "Filesystem solicitado não atende política ativa.",
        "Aplicar apenas formatos permitidos.",
        stage="policy", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=True,
        short_pt="Violação de política de filesystem.",
        detailed_pt="A solicitação de formatação viola a política operacional vigente.",
        probable_causes_pt=["Parâmetro de filesystem inválido.", "Solicitação fora da política de produto."],
        recommended_actions_pt=["Corrigir parâmetro de entrada.", "Executar somente formatos permitidos."],
    ),
    "MS-POL-002": ErrorSpec(
        "MS-POL-002", "POL", "ReadyStateContractViolation", "ERROR", False,
        "Estado READY em desacordo com contrato.",
        "Critérios mínimos de prontidão não satisfeitos.",
        "Revalidar evidências antes de marcar READY.",
        stage="policy", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=True,
        short_pt="Violação do contrato READY.",
        detailed_pt="O disco não possui evidências suficientes para estado READY seguro.",
        probable_causes_pt=["Critérios permissivos de avaliação.", "Evidência incompleta no pós-check."],
        recommended_actions_pt=["Exigir critérios completos de prontidão.", "Bloquear READY sem evidência mínima."],
    ),
    "MS-POL-003": ErrorSpec(
        "MS-POL-003", "POL", "InternalDiskOperationForbidden", "CRITICAL", False,
        "Operação em disco interno é proibida.",
        "Tentativa de operar fora do escopo permitido.",
        "Bloquear execução e revisar seleção.",
        stage="policy", severity_level=4, severity_label="CRITICAL", retryable=False, integrity_impact=True,
        short_pt="Operação proibida em disco interno.",
        detailed_pt="A política bloqueou operação potencialmente destrutiva em disco não elegível.",
        probable_causes_pt=["Seleção de disco incorreta.", "Bypass de validação de elegibilidade."],
        recommended_actions_pt=["Interromper execução imediatamente.", "Selecionar apenas mídia removível elegível."],
    ),

    "MS-SYS-001": ErrorSpec(
        "MS-SYS-001", "SYS", "AdminPrivilegesRequired", "ERROR", False,
        "Privilégios de administrador são obrigatórios.",
        "Execução sem elevação suficiente.",
        "Executar processo com privilégios administrativos.",
        stage="system", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=False,
        short_pt="Privilégios administrativos ausentes.",
        detailed_pt="A operação exige privilégios elevados para comandos de disco.",
        probable_causes_pt=["Processo sem elevação.", "Contexto de execução restrito."],
        recommended_actions_pt=["Reiniciar aplicação como administrador."],
    ),
    "MS-SYS-003": ErrorSpec(
        "MS-SYS-003", "SYS", "RequiredAssetMissing", "ERROR", False,
        "Asset obrigatório não encontrado.",
        "Script/binário requerido está ausente.",
        "Restaurar arquivos obrigatórios do pacote.",
        stage="system", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=False,
        short_pt="Asset obrigatório ausente.",
        detailed_pt="Um artefato necessário para o pipeline não foi localizado.",
        probable_causes_pt=["Instalação incompleta.", "Caminho de assets inválido."],
        recommended_actions_pt=["Revalidar instalação dos assets.", "Corrigir path configurado."],
    ),

    "MS-CFG-001": ErrorSpec(
        "MS-CFG-001", "CFG", "InvalidOperationConfiguration", "ERROR", False,
        "Configuração de operação inválida.",
        "Parâmetros de execução não atendem contrato.",
        "Corrigir configuração antes de executar.",
        stage="config", severity_level=3, severity_label="ERROR", retryable=False, integrity_impact=False,
        short_pt="Configuração operacional inválida.",
        detailed_pt="A configuração recebida não atende pré-condições de execução.",
        probable_causes_pt=["Parâmetro obrigatório ausente.", "Valor fora de faixa esperada."],
        recommended_actions_pt=["Validar configuração antes do start.", "Aplicar normalização de entrada."],
    ),

    "MS-AUD-001": ErrorSpec(
        "MS-AUD-001", "AUD", "AuditWriteFailure", "WARN", True,
        "Falha ao gravar evento de auditoria.",
        "IO/log path inválido.",
        "Corrigir diretório de logs/permissões.",
        stage="audit", severity_level=1, severity_label="WARN", retryable=True, integrity_impact=False,
        short_pt="Falha de escrita na auditoria.",
        detailed_pt="O evento de auditoria não pôde ser persistido no log principal.",
        probable_causes_pt=["Permissão insuficiente no diretório de logs.", "Path inválido para persistência."],
        recommended_actions_pt=["Corrigir permissões de escrita.", "Validar diretório de auditoria."],
    ),

    "MS-USB-003": ErrorSpec(
        "MS-USB-003", "USB", "RemovableDeviceNotReacquired", "ERROR", True,
        "Dispositivo removível não foi re-adquirido.",
        "Reenumeração/desconexão durante operação.",
        "Reconectar dispositivo e tentar novamente.",
        stage="usb", severity_level=3, severity_label="ERROR", retryable=True, integrity_impact=True,
        short_pt="Dispositivo removível não re-adquirido.",
        detailed_pt="O dispositivo alvo não foi localizado após etapa crítica.",
        probable_causes_pt=["Desconexão física durante operação.", "Reenumeração sem correspondência de identidade."],
        recommended_actions_pt=["Reconectar mídia e atualizar snapshot.", "Reexecutar validação de identidade."],
    ),
}