SUPPORTED_FILESYSTEMS = ["FAT32", "exFAT"]

STATUS_READY = "READY"
STATUS_NEEDS_PREPARATION = "NEEDS_PREPARATION"
STATUS_BLOCKED = "BLOCKED"
STATUS_OFFLINE = "OFFLINE"
STATUS_WARNING = "WARNING_OS_PRESENT"
STATUS_INCOMPATIBLE = "INCOMPATIBLE"