SUPPORTED_FILESYSTEMS = ["FAT32", "EXFAT"]

# Status legacy (compatibilidade)
STATUS_READY = "READY"
STATUS_NEEDS_PREPARATION = "NEEDS_PREPARATION"
STATUS_BLOCKED = "BLOCKED"
STATUS_OFFLINE = "OFFLINE"
STATUS_WARNING = "WARNING_OS_PRESENT"
STATUS_INCOMPATIBLE = "INCOMPATIBLE"

# Status arquiteturais determinísticos
STATUS_NOT_INITIALIZED = "NOT_INITIALIZED"
STATUS_RAW = "RAW"
STATUS_WRONG_PARTITION_STYLE = "WRONG_PARTITION_STYLE"
STATUS_WRONG_FILESYSTEM = "WRONG_FILESYSTEM"
STATUS_INVALID_DISK = "INVALID_DISK"
STATUS_SYSTEM_DISK = "SYSTEM_DISK"
